In [36]:
import pandas as pd
from itertools import chain
from collections import Counter
df_teste01 = pd.read_csv('../data/txtlimpo01.csv')
df_teste01.head()

   Unnamed: 0                                        Texto limpo
0           0   a comunicante acima qualificada compareceu ne...
1           1     a comunicante acima qualificada compareceu ...
2           2   a relatora atualmente com   anos de idade vem...
3           3   relata que ha aproximadamente dois meses ao a...
4           4    a idosa   anos e deficiente fisica anda de c...

In [40]:
lista_de_palavras = Counter(chain.from_iterable(df_teste01['Texto limpo'].apply(lambda x: x.split()).tolist()))
cont_palavras = pd.DataFrame(lista_de_palavras.items(), columns = ['valor', 'contagem'])
cont_palavras

             valor  contagem
0                a      4598
1      comunicante       113
2            acima       385
3      qualificada       110
4       compareceu       183
...            ...       ...
8680     empurrala         1
8681    imobilizou         1
8682      segurala         1
8683  intercederam         1
8684      soltasse         1

[8685 rows x 2 columns]

Tratamento de dados da versão 1 foi ineficiente